### ISSUE TITLE
中文问题

### ISSUE THREAD

**Issue by leviathan0992** [Leviathan1995/Pylsy#32]
@Arthur2e5 

t = pylsytable([u'name', u'love'])
    t.add_data('name', [u'小明', 'Alice'])
    t.add_data('love', [u'搞比利！', u'啊'])
    print(t)

Traceback (most recent call last):
  File "/Users/Leviathan/PycharmProjects/pylsy/pylsy.py", line 129, in <module>
    main()
  File "/Users/Leviathan/PycharmProjects/pylsy/pylsy.py", line 126, in main
    print(t)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 101-102: ordinal not in range(128)

**Comment by Artoria2e5** [comment]
Use `print t.__str__()` instead.

**Comment by Artoria2e5** [comment]
By the way I should write a `__unicode__()`……

**Comment by Leviathan1995** [comment]
File "/Users/Leviathan/PycharmProjects/pylsy/pylsy.py", line 126
    print t.__str__()
          ^
SyntaxError: invalid syntax

**Comment by Leviathan1995** [comment]
File "/Users/Leviathan/PycharmProjects/pylsy/pylsy.py", line 126
    print t.__str__()
          ^
SyntaxError: invalid syntax

**Comment by Leviathan1995** [comment]
File "/Users/Leviathan/PycharmProjects/pylsy/pylsy.py", line 126
'''
    print t.__str__()
'''
          ^
SyntaxError: invalid syntax

**Comment by Leviathan1995** [comment]
File "/Users/Leviathan/PycharmProjects/pylsy/pylsy.py", line 126
```
    print t.__str__()
```
          ^
SyntaxError: invalid syntax

**Comment by Artoria2e5** [comment]
Interesting, grabbing Python 3.

**Comment by leviathan0992** [comment]
File "/Users/Leviathan/PycharmProjects/pylsy/pylsy.py", line 126
   `print t.__str__()`
          ^
SyntaxError: invalid syntax

**Comment by leviathan0992** [comment]
....

**Comment by Artoria2e5** [comment]
`print(t.__str__())` then. By the way I figured out that I don't need to write `__unicode__()`.

**Comment by leviathan0992** [comment]
right

**Comment by Artoria2e5** [comment]
Let me document this in README.md.

**Comment by Artoria2e5** [comment]
有时候我总觉得该直接用个 collections.orderedDict()……
